/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TymRouteImport } from './routes/tym'
import { Route as NaboryRouteImport } from './routes/nabory'
import { Route as HlasovaniRouteImport } from './routes/hlasovani'
import { Route as BanlistRouteImport } from './routes/banlist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TymRoute = TymRouteImport.update({
  id: '/tym',
  path: '/tym',
  getParentRoute: () => rootRouteImport,
} as any)
const NaboryRoute = NaboryRouteImport.update({
  id: '/nabory',
  path: '/nabory',
  getParentRoute: () => rootRouteImport,
} as any)
const HlasovaniRoute = HlasovaniRouteImport.update({
  id: '/hlasovani',
  path: '/hlasovani',
  getParentRoute: () => rootRouteImport,
} as any)
const BanlistRoute = BanlistRouteImport.update({
  id: '/banlist',
  path: '/banlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banlist': typeof BanlistRoute
  '/hlasovani': typeof HlasovaniRoute
  '/nabory': typeof NaboryRoute
  '/tym': typeof TymRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banlist': typeof BanlistRoute
  '/hlasovani': typeof HlasovaniRoute
  '/nabory': typeof NaboryRoute
  '/tym': typeof TymRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/banlist': typeof BanlistRoute
  '/hlasovani': typeof HlasovaniRoute
  '/nabory': typeof NaboryRoute
  '/tym': typeof TymRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/banlist'
    | '/hlasovani'
    | '/nabory'
    | '/tym'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/banlist' | '/hlasovani' | '/nabory' | '/tym' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/banlist'
    | '/hlasovani'
    | '/nabory'
    | '/tym'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BanlistRoute: typeof BanlistRoute
  HlasovaniRoute: typeof HlasovaniRoute
  NaboryRoute: typeof NaboryRoute
  TymRoute: typeof TymRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tym': {
      id: '/tym'
      path: '/tym'
      fullPath: '/tym'
      preLoaderRoute: typeof TymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nabory': {
      id: '/nabory'
      path: '/nabory'
      fullPath: '/nabory'
      preLoaderRoute: typeof NaboryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hlasovani': {
      id: '/hlasovani'
      path: '/hlasovani'
      fullPath: '/hlasovani'
      preLoaderRoute: typeof HlasovaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banlist': {
      id: '/banlist'
      path: '/banlist'
      fullPath: '/banlist'
      preLoaderRoute: typeof BanlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BanlistRoute: BanlistRoute,
  HlasovaniRoute: HlasovaniRoute,
  NaboryRoute: NaboryRoute,
  TymRoute: TymRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
